---
- name: 
  hosts: all
  tasks:
    - ansible.builtin.uri:
        url: https://izckho78op95fjqrtt9bjc.hooks.webhookrelay.com
        method: POST
        body_format: json
        src: files/fake-alert.json
