- name: EDA Hackathon Playbook
  hosts: localhost
  connection: local
  gather_facts: false

  tasks:
    - name: Print variable event set by rulebook engine
      ansible.builtin.debug:
        msg: '{{ ansible_eda.event }}'
